### ISSUE TITLE
FRBlackmun push access

### ISSUE THREAD

**Issue by FRBlackmun** [societies/SOCIETIES-SCE-Services#1]
Can my account FRBlackmun be added to the 3P services repository? I can't push right now. Thanks

**Comment by yboul** [comment]
Hi Fraser,
I just emailed Alec and hopefully he will soon grant you permissions to 
push to 3p services repository in github.

Kind regards,
Yiorgos

**Comment by EPapadopoulou** [comment]
Hi Fraser, 
   You need to contact Alec and ask him to add your account information to the list of authorised developers for the 3p repository. 

Eliza

-----Original Message-----
From: FRBlackmun [mailto:reply@reply.github.com] 
Sent: 02 July 2012 20:22
To: Papadopoulou, Elizabeth
Subject: [SOCIETIES-SCE-Services] FRBlackmun push access (#1)

Can my account FRBlackmun be added to the 3P services repository? I can't push right now. Thanks

---

Reply to this email directly or view it on GitHub:
https://github.com/societies/SOCIETIES-SCE-Services/issues/1

## 

Heriot-Watt University is the Sunday Times
Scottish University of the Year 2011-2012

Heriot-Watt University is a Scottish charity
registered under charity number SC000278.

**Comment by KorbinianFrank** [comment]
Hi Fraser,

I guess you wanted to ask that rather Alec than me...

Have a nice evening,
Korbinian

-----Original Message-----
From: FRBlackmun [mailto:reply@reply.github.com] 
Sent: Monday, July 02, 2012 9:22 PM
To: Frank, Korbinian
Subject: [SOCIETIES-SCE-Services] FRBlackmun push access (#1)

Can my account FRBlackmun be added to the 3P services repository? I can't push right now. Thanks

---

Reply to this email directly or view it on GitHub:
https://github.com/societies/SOCIETIES-SCE-Services/issues/1

**Comment by JacquelineFloch** [comment]
Hi Fraser

I think that you made a mistake when sending this email.I have not the
authority to change access rights to the repository. You should contact
Alec or Gerd.

Cheers
Jacqueline

On 02 Jul 12 21:22 , "FRBlackmun"
<reply+i-5393095-545951482329c0d39c9c50f5b60b2cbefe5f745b-1140207@reply.git
hub.com> wrote:

**Comment by dmckitterick** [comment]
Fraser,

Alec has already added you so you should be able to do what you need.

Regards,
David.

-----Original Message-----
From: FRBlackmun [mailto:reply@reply.github.com] 
Sent: Monday, July 02, 2012 8:22 PM
To: Mckitterick, DavidX
Subject: [SOCIETIES-SCE-Services] FRBlackmun push access (#1)

Can my account FRBlackmun be added to the 3P services repository? I can't push right now. Thanks

---

Reply to this email directly or view it on GitHub:

## https://github.com/societies/SOCIETIES-SCE-Services/issues/1

Intel Ireland Limited (Branch)
Collinstown Industrial Park, Leixlip, County Kildare, Ireland
Registered Number: E902934

This e-mail and any attachments may contain confidential material for
the sole use of the intended recipient(s). Any review or distribution
by others is strictly prohibited. If you are not the intended
recipient, please contact the sender and delete all copies.

**Comment by FRBlackmun** [comment]
Sorry everyone,

I didn't know who to contact so I set up an 'issue' on Github. I didn't 
realise it sends an email to everyone watching the repository. Thanks 
Alec for giving me access.

Regards
- Fraser

On 03/07/2012 08:16, JacquelineFloch wrote:

> Hi Fraser
> 
> I think that you made a mistake when sending this email.I have not the
> authority to change access rights to the repository. You should contact
> Alec or Gerd.
> 
> Cheers
> Jacqueline
> 
> On 02 Jul 12 21:22 , "FRBlackmun"
> <reply+i-5393095-545951482329c0d39c9c50f5b60b2cbefe5f745b-1140207@reply.git
> hub.com> wrote:
> 
> > Can my account FRBlackmun be added to the 3P services repository? I can't
> > push right now. Thanks
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > ## https://github.com/societies/SOCIETIES-SCE-Services/issues/1
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/societies/SOCIETIES-SCE-Services/issues/1#issuecomment-6727561

## 

Heriot-Watt University is the Sunday Times
Scottish University of the Year 2011-2012

Heriot-Watt University is a Scottish charity
registered under charity number SC000278.

**Comment by mcrotty** [comment]
Hi David,

Can you enable push access to this for Frasier?

Regards,
Micheal

On Mon, 2012-07-02 at 12:22 -0700, FRBlackmun wrote:

> Can my account FRBlackmun be added to the 3P services repository? I can't push right now. Thanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/societies/SOCIETIES-SCE-Services/issues/1

## 

Phone:+353 51 302939  Skype:mcrotty
